name: Build and Dockerize with PNPM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install PNPM
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Build with Turbo
        run: pnpm build

      - name: Build Docker image
        run: docker build . -t my-app:latest

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: docker push ghcr.io/${{ github.repository }}/my-app:latest
